MinGW workaround

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -246,12 +246,9 @@ error() {
 
 echo
 
-# mingw has problems opening /dev/null and gives false negative
-if echo "uh, nothing works on Windows" | tee /dev/null > /dev/null; then
-    # basic check
-    if ! echo "int main(){}" | "$CC" -xc -std=c99 -o /dev/null - > /dev/null; then
-        error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
-    fi
+# /tmp, because mingw has problems opening /dev/null and gives false negative
+if ! echo "int main(){}" | "$CC" -xc -std=c99 -o /tmp/gcccheck - > /dev/null; then
+    error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
 fi
 
 status "Compiler" "$CC"
