Hack gcc check for Windows

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -246,9 +246,12 @@ error() {
 
 echo
 
-# basic check
-if ! echo "int main(){}" | "$CC" -xc -std=c99 -o /dev/null - > /dev/null; then
-    error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
+# mingw has problems opening /dev/null and gives false negative
+if echo "uh, nothing works on Windows" | tee /dev/null > /dev/null; then
+    # basic check
+    if ! echo "int main(){}" | "$CC" -xc -std=c99 -o /dev/null - > /dev/null; then
+        error "Compiler" "$CC failed to compile anything (make sure it's installed and supports C99)"
+    fi
 fi
 
 status "Compiler" "$CC"
